version: "3.9"
services:
  db:
    # https://hub.docker.com/_/postgres/
    image: postgres:latest
    restart: always
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./tmp/db:/var/lib/postgresql/data
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tododatabase
  web:
    image: todo-list_web
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      POSTGRES_URL: postgres://postgres:postgres@db:8080/tododatabase
    